"""
gcode_writer.py — Convert toolpaths to G-code for concrete 3D printing.

Outputs Marlin/RepRap-style G-code suitable for most 3DCP printers.
Key parameters configurable via PrintSettings.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import List, TextIO

from .toolpath import ExtrusionSegment, LayerToolpath, ToolpathResult, TravelMove


@dataclass
class PrintSettings:
    """Printer-specific settings for G-code generation."""

    # Printer bed / workflow
    print_area_mm: List[float] = field(default_factory=lambda: [3000, 3000, 4000])  # X, Y, Z
    z_hop_mm: float = 5.0  # safe Z hop between islands
    filament_diameter_mm: float = 3.0
    nozzle_diameter_mm: float = 6.0
    extrusion_multiplier: float = 1.0  # flow rate tweak

    # Speeds (mm/min)
    travel_speed: int = 6000
    first_layer_speed: int = 1200
    print_speed: int = 1800

    # Pre/Post
    pre_gcode: str = ""  # run before print
    post_gcode: str = ""  # run after print


def _calculate_e(
    segment: ExtrusionSegment,
    settings: PrintSettings,
    is_first_layer: bool = False,
) -> float:
    """Calculate E value from move distance and extrusion geometry."""
    e = segment.e * settings.extrusion_multiplier
    return round(e, 6)


def _write_header(f: TextIO, settings: PrintSettings, total_layers: int):
    """Write G-code preamble."""
    f.write("; G-code generated by bim-to-print v0.1.0\n")
    f.write(f"; Nozzle: {settings.nozzle_diameter_mm}mm\n")
    f.write(f"; Filament: {settings.filament_diameter_mm}mm\n")
    f.write("; ----------------------------------------\n")
    f.write("G21 ; millimetres\n")
    f.write("G90 ; absolute positioning\n")
    f.write("M82 ; absolute extrusion\n")
    f.write("G28 ; home all axes\n")
    if settings.pre_gcode:
        for line in settings.pre_gcode.strip().split("\n"):
            f.write(f"{line.strip()}\n")
    f.write("G1 Z5.0 F3000 ; lift nozzle\n")
    f.write("; ----------------------------------------\n\n")


def _write_footer(f: TextIO, settings: PrintSettings):
    """Write G-code postamble."""
    f.write("\n; ----------------------------------------\n")
    f.write("G91 ; relative positioning\n")
    f.write("G1 Z10.0 F3000 ; lift nozzle\n")
    f.write("G90 ; absolute positioning\n")
    f.write("M84 ; disable motors\n")
    if settings.post_gcode:
        for line in settings.post_gcode.strip().split("\n"):
            f.write(f"{line.strip()}\n")
    f.write("; Print complete\n")


def _write_layer(
    f: TextIO, layer: LayerToolpath, settings: PrintSettings, layer_idx: int
):
    """Write one layer's worth of G-code."""
    is_first = layer_idx == 0
    f.write(f"; --- Layer {layer_idx + 1} — Z={layer.z:.2f} ---\n")
    f.write(f"; Profile: {layer.profile_name}\n")

    for move in layer.moves:
        if isinstance(move, TravelMove):
            f.write(
                f"G0 X{move.x:.2f} Y{move.y:.2f} Z{move.z:.2f} F{settings.travel_speed}\n"
            )
        elif isinstance(move, ExtrusionSegment):
            e_val = _calculate_e(move, settings, is_first)
            speed = settings.first_layer_speed if is_first else settings.print_speed
            f.write(
                f"G1 X{move.x:.2f} Y{move.y:.2f} Z{move.z:.2f} "
                f"E{e_val} F{speed}\n"
            )
    f.write("\n")


def write_gcode(
    result: ToolpathResult,
    output_path: str,
    settings: PrintSettings | None = None,
):
    """Write a complete G-code file from a ToolpathResult.

    Args:
        result: Toolpath output from toolpath.generate_toolpath().
        output_path: Path to write .gcode file.
        settings: Printer settings (defaults used if None).
    """
    if settings is None:
        settings = PrintSettings()

    with open(output_path, "w") as f:
        _write_header(f, settings, len(result.layer_paths))
        for idx, lp in enumerate(result.layer_paths):
            _write_layer(f, lp, settings, idx)
        _write_footer(f, settings)


def write_gcode_string(
    result: ToolpathResult,
    settings: PrintSettings | None = None,
) -> str:
    """Return G-code as a string (for testing / embedding)."""
    import io

    buf = io.StringIO()
    if settings is None:
        settings = PrintSettings()
    _write_header(buf, settings, len(result.layer_paths))
    for idx, lp in enumerate(result.layer_paths):
        _write_layer(buf, lp, settings, idx)
    _write_footer(buf, settings)
    return buf.getvalue()
